# Generated by Django 4.0.1 on 2022-01-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=20)),
                ('Age', models.IntegerField(default='')),
                ('Email', models.EmailField(default='', max_length=254)),
                ('Password', models.CharField(default='', max_length=12)),
                ('Photo', models.ImageField(default='', upload_to='media/')),
            ],
        ),
    ]
